"use client";
import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { loadWorkstreams, labelFromKey, workstreamKey, SCOPE_PREFIX, type Workstream } from "@/lib/consultation-workstreams";

export type CPProject={id:string;organization_id:string;name:string;project_type:string|null;baseline_start:string|null;target_finish:string|null;original_budget:number|null;status:string};
export type CPEvent={id:string;event_type:string;title:string;description:string|null;start_at:string|null;status:string|null;cost_impact:number|null;schedule_impact_days:number|null};
export type CPEvidence={id:string;title:string|null;evidence_type:string;source_system:string|null;occurred_at:string|null;raw_text:string|null;created_at:string;storage_path?:string|null};
export type CPCompany={id:string;name:string;company_type:string|null};

const fmt=(v:string|null)=>v?new Date(v.includes("T")?v:v+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):"Not set";
const money=(v:number|null|undefined)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);

export function ReviewInbox({projectId,refresh}:{projectId:string;refresh:()=>void}){
 const[streams,setStreams]=useState<Workstream[]>([]),[candidates,setCandidates]=useState<any[]>([]),[edits,setEdits]=useState<Record<string,any>>({}),[message,setMessage]=useState("");
 async function load(){const s=createClient();const r=await s.from("extraction_candidates").select("id,candidate_type,candidate_key,proposed_value,confidence,status,created_at").eq("project_id",projectId).eq("status","pending").order("created_at",{ascending:false});setCandidates(r.data||[])}
 useEffect(()=>{load();loadWorkstreams(projectId).then(setStreams)},[projectId]);
 function value(c:any){return edits[c.id]||c.proposed_value||{}}
 function patch(c:any,key:string,v:any){setEdits(x=>({...x,[c.id]:{...value(c),[key]:v}}))}
 async function saveEdit(c:any){const s=createClient(),v=value(c);const r=await s.from("extraction_candidates").update({proposed_value:v}).eq("id",c.id);if(r.error)setMessage(r.error.message);else setMessage("Candidate updated.")}
 async function reject(c:any){const s=createClient(),u=await s.auth.getUser();await s.from("extraction_candidates").update({status:"rejected",reviewed_by:u.data.user?.id||null,reviewed_at:new Date().toISOString()}).eq("id",c.id);await load()}
 async function confirm(c:any){const s=createClient(),v=value(c),u=await s.auth.getUser();
  if((v.subtype||c.candidate_key)==="milestone"){
   const m=await s.from("consultation_workstream_milestones").insert({project_id:projectId,workstream_key:(streams.some(w=>w.key===v.workstream_key)?v.workstream_key:streams[0]?.key)||"general",title:v.title||"Suggested milestone",description:v.description||v.source_quote||null,target_date:v.target_date||null,status:v.status||"not_started",owner:v.owner||null,scope_origin:v.scope_origin||"original",created_by:u.data.user?.id||null}).select("id").single();
   if(m.error){setMessage(m.error.message);return}
   if(v.evidence_id)await s.from("evidence_links").insert({evidence_id:v.evidence_id,entity_type:"consultation_workstream_milestone",entity_id:m.data.id,relationship:"supports"});
   await s.from("extraction_candidates").update({status:"accepted",proposed_value:v,reviewed_by:u.data.user?.id||null,reviewed_at:new Date().toISOString()}).eq("id",c.id);
   setMessage("Milestone confirmed and added to the workstream.");await load();refresh();return;
  }
  const e=await s.from("project_events").insert({project_id:projectId,event_type:v.subtype||c.candidate_type||"change",title:v.title||"Meeting insight",description:v.description||v.source_quote||null,start_at:v.date||new Date().toISOString().slice(0,10),date_precision:"day",status:v.status||"open",cost_impact:Number(v.cost_impact)||0,schedule_impact_days:Number(v.schedule_impact_days)||0,created_by:u.data.user?.id||null}).select("id").single();if(e.error){setMessage(e.error.message);return}if(v.evidence_id)await s.from("evidence_links").insert({evidence_id:v.evidence_id,entity_type:"project_event",entity_id:e.data.id,relationship:"supports"});await s.from("extraction_candidates").update({status:"accepted",proposed_value:v,reviewed_by:u.data.user?.id||null,reviewed_at:new Date().toISOString()}).eq("id",c.id);setMessage("Confirmed and added to the engagement history.");await load();refresh()}
 return <section className="cp-card"><div className="cp-card-head"><div><p className="cp-kicker">MEETING REVIEW INBOX</p><h2>Confirm what the meeting changed</h2><p className="cp-muted">Nothing becomes an official engagement fact until you confirm it.</p></div><span className="cp-count">{candidates.length} pending</span></div>{message&&<div className="cp-message">{message}</div>}{candidates.map(c=>{const v=value(c);return <article className="cp-candidate" key={c.id}><div className="cp-candidate-top"><span>{v.subtype||c.candidate_type}</span><small>{Math.round((Number(c.confidence)||.7)*100)}% confidence</small></div><label>Title<input value={v.title||""} onChange={e=>patch(c,"title",e.target.value)}/></label><label>What was said<textarea value={v.source_quote||v.description||""} onChange={e=>patch(c,"description",e.target.value)}/></label><div className="cp-candidate-grid"><label>Type<select value={v.subtype||"change"} onChange={e=>patch(c,"subtype",e.target.value)}><option value="change">Scope change</option><option value="decision">Decision</option><option value="dependency">Client dependency</option><option value="commitment">Commitment</option><option value="risk">Risk</option><option value="milestone">Milestone</option></select></label>{v.subtype==="milestone"?<><label>Workstream<select value={streams.some(w=>w.key===v.workstream_key)?v.workstream_key:streams[0]?.key||""} onChange={e=>patch(c,"workstream_key",e.target.value)}>{streams.map(w=><option key={w.key} value={w.key}>{w.label}</option>)}</select></label><label>Target date<input type="date" value={v.target_date||""} onChange={e=>patch(c,"target_date",e.target.value)}/></label><label>Owner<input value={v.owner||""} onChange={e=>patch(c,"owner",e.target.value)} placeholder="Owner"/></label><label>Scope origin<select value={v.scope_origin||"original"} onChange={e=>patch(c,"scope_origin",e.target.value)}><option value="original">Original scope</option><option value="added">Added later</option></select></label></>:<><label>Schedule impact<input type="number" value={v.schedule_impact_days??0} onChange={e=>patch(c,"schedule_impact_days",e.target.value)}/></label><label>Fee impact<input value={v.cost_impact??0} onChange={e=>patch(c,"cost_impact",e.target.value)}/></label></>}</div><div className="cp-candidate-actions"><button className="cp-link" onClick={()=>saveEdit(c)}>Save edit</button><button className="cp-secondary" onClick={()=>reject(c)}>Reject</button><button className="cp-primary" onClick={()=>confirm(c)}>Confirm →</button></div></article>})}{!candidates.length&&<p className="cp-empty">No meeting insights are waiting for review.</p>}</section>
}

export function ChangeRegister({events,refresh}:{events:CPEvent[];refresh:()=>void}){
 const rows=events.filter(e=>!["baseline","meeting"].includes(e.event_type));const[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState<any>({}),[message,setMessage]=useState("");
 function open(e:CPEvent){setEditing(e.id);setDraft({...e,start_at:e.start_at?.slice(0,10)||""})}
 async function save(){const s=createClient();const r=await s.from("project_events").update({event_type:draft.event_type,title:draft.title,description:draft.description||null,start_at:draft.start_at||null,status:draft.status||null,schedule_impact_days:Number(draft.schedule_impact_days)||0,cost_impact:Number(draft.cost_impact)||0}).eq("id",editing);if(r.error){setMessage(r.error.message);return}setEditing(null);refresh()}
 async function remove(id:string){if(!window.confirm("Delete this engagement record?"))return;const s=createClient();const r=await s.from("project_events").delete().eq("id",id);if(r.error)setMessage(r.error.message);else refresh()}
 return <section className="cp-card"><p className="cp-kicker">CHANGE REGISTER</p><h2>Changes, decisions and dependencies</h2>{message&&<div className="cp-message">{message}</div>}<div className="cp-table cp-table-actions"><div className="head"><span>Date</span><span>Type</span><span>Item</span><span>Status</span><span>Days</span><span>Fee</span><span/></div>{rows.map(e=><div key={e.id}><span>{fmt(e.start_at)}</span><span>{e.event_type}</span><span><strong>{e.title}</strong><small>{e.description}</small></span><span>{e.status||"open"}</span><span>{e.schedule_impact_days||0}</span><span>{money(e.cost_impact)}</span><span className="cp-row-actions"><button onClick={()=>open(e)}>Edit</button><button onClick={()=>remove(e.id)}>Delete</button></span></div>)}</div>{editing&&<div className="cp-edit-drawer"><h3>Edit engagement record</h3><div className="cp-entry-grid"><label>Type<select value={draft.event_type||""} onChange={e=>setDraft({...draft,event_type:e.target.value})}><option value="change">Scope change</option><option value="decision">Decision</option><option value="dependency">Client dependency</option><option value="commitment">Commitment</option><option value="risk">Risk</option><option value="milestone">Milestone</option></select></label><label>Date<input type="date" value={draft.start_at||""} onChange={e=>setDraft({...draft,start_at:e.target.value})}/></label><label className="wide">Title<input value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="wide">Details<textarea value={draft.description||""} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Schedule impact<input type="number" value={draft.schedule_impact_days??0} onChange={e=>setDraft({...draft,schedule_impact_days:e.target.value})}/></label><label>Fee impact<input value={draft.cost_impact??0} onChange={e=>setDraft({...draft,cost_impact:e.target.value})}/></label><label>Status<input value={draft.status||""} onChange={e=>setDraft({...draft,status:e.target.value})}/></label></div><div className="cp-entry-actions"><button className="cp-secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="cp-primary" onClick={save}>Save changes</button></div></div>}</section>
}

export function EvidenceLibrary({projectId,evidence,refresh}:{projectId:string;evidence:CPEvidence[];refresh:()=>void}){
 const[file,setFile]=useState<File|null>(null),[title,setTitle]=useState(""),[message,setMessage]=useState("");
 async function upload(){if(!file)return;const s=createClient(),u=await s.auth.getUser(),safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,"-"),path=projectId+"/"+crypto.randomUUID()+"-"+safe;const up=await s.storage.from("project-evidence").upload(path,file,{contentType:file.type||undefined,upsert:false});if(up.error){setMessage(up.error.message);return}const ev=await s.from("evidence").insert({project_id:projectId,evidence_type:"document",title:title||file.name,source_system:"upload",storage_path:path,metadata:{file_name:file.name,mime_type:file.type,size:file.size},created_by:u.data.user?.id||null});if(ev.error){setMessage(ev.error.message);return}setFile(null);setTitle("");setMessage("Evidence uploaded.");refresh()}
 async function remove(e:CPEvidence){if(!window.confirm("Delete this evidence record?"))return;const s=createClient();if(e.storage_path)await s.storage.from("project-evidence").remove([e.storage_path]);const r=await s.from("evidence").delete().eq("id",e.id);if(r.error)setMessage(r.error.message);else refresh()}
 return <section className="cp-card"><p className="cp-kicker">SOURCE EVIDENCE</p><h2>Documents that support the engagement story</h2><p className="cp-muted">Upload the SOW, approvals, requirements, UAT material, screenshots, spreadsheets and supporting correspondence.</p><div className="cp-evidence-upload"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Evidence title (optional)"/><label className="cp-upload">Choose file<input type="file" onChange={(e:ChangeEvent<HTMLInputElement>)=>setFile(e.target.files?.[0]||null)}/></label><span>{file?.name||"No file selected"}</span><button className="cp-primary" disabled={!file} onClick={upload}>Upload evidence</button></div>{message&&<div className="cp-message">{message}</div>}{evidence.map(x=><div className="cp-evidence" key={x.id}><div><strong>{x.title||x.evidence_type}</strong><span>{x.source_system||x.evidence_type} · {fmt(x.occurred_at||x.created_at)}</span></div><button className="cp-link" onClick={()=>remove(x)}>Delete</button></div>)}{!evidence.length&&<p className="cp-empty">No evidence uploaded yet.</p>}</section>
}

export function EngagementEditor({project,companies,refresh}:{project:CPProject;companies:CPCompany[];refresh:()=>void}){
 const client=companies.find(c=>c.company_type==="client");const[form,setForm]=useState({name:project.name,start:project.baseline_start||"",finish:project.target_finish||"",budget:String(project.original_budget||""),client:client?.name||""});
 const[streams,setStreams]=useState<Workstream[]>([]),[scope,setScope]=useState<Record<string,string>>({}),[newStream,setNewStream]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{(async()=>{const list=await loadWorkstreams(project.id);const r=await createClient().from("project_requirements").select("requirement_key,enabled,notes").eq("project_id",project.id).like("requirement_key",SCOPE_PREFIX+"%");const x:Record<string,string>={};for(const w of list)x[w.key]="baseline";for(const row of r.data||[]){const k=String(row.requirement_key).slice(SCOPE_PREFIX.length);x[k]=row.enabled?(row.notes==="added"?"added":"baseline"):"none"}setStreams(list);setScope(x)})()},[project.id]);
 function addStream(){const label=newStream.trim();if(!label)return;let key=workstreamKey(label);while(streams.some(w=>w.key===key))key=key+"_2";setStreams([...streams,{key,label}]);setScope({...scope,[key]:"added"});setNewStream("")}
 function rename(key:string,label:string){setStreams(streams.map(w=>w.key===key?{...w,label}:w))}
 async function save(){const s=createClient();const p=await s.from("projects").update({name:form.name,baseline_start:form.start||null,target_finish:form.finish||null,original_budget:form.budget?Number(form.budget.replace(/[^0-9.-]/g,"")):null,updated_at:new Date().toISOString()}).eq("id",project.id);if(p.error){setMessage(p.error.message);return}if(client)await s.from("companies").update({name:form.client}).eq("id",client.id);else if(form.client)await s.from("companies").insert({organization_id:project.organization_id,name:form.client,company_type:"client"});for(const w of streams){const mode=scope[w.key]||"none";const r=await s.from("project_requirements").upsert({project_id:project.id,requirement_key:SCOPE_PREFIX+w.key,label:w.label.trim()||labelFromKey(w.key),enabled:mode!=="none",source:"user",notes:mode==="added"?"added":"baseline",updated_at:new Date().toISOString()},{onConflict:"project_id,requirement_key"});if(r.error){setMessage(r.error.message);return}}setMessage("Engagement baseline and workstreams updated.");refresh()}
 return <section className="cp-card"><p className="cp-kicker">ENGAGEMENT DATA</p><h2>Edit the original baseline and scope</h2><div className="cp-entry-grid"><label className="wide">Engagement name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Client<input value={form.client} onChange={e=>setForm({...form,client:e.target.value})}/></label><label>Original contract value<input value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}/></label><label>Kickoff<input type="date" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></label><label>Original go-live<input type="date" value={form.finish} onChange={e=>setForm({...form,finish:e.target.value})}/></label></div><div className="cp-scope-editor"><p className="cp-kicker">WORKSTREAMS &amp; SCOPE</p><p className="cp-muted">Rename these to match how you scope the work, or add your own. Mark each as original scope, added later, or not in scope.</p>{streams.map(w=><label key={w.key}><input aria-label="Workstream name" value={w.label} onChange={e=>rename(w.key,e.target.value)}/><select value={scope[w.key]||"baseline"} onChange={e=>setScope({...scope,[w.key]:e.target.value})}><option value="baseline">Original scope</option><option value="added">Added later</option><option value="none">Not in scope</option></select></label>)}<label><input value={newStream} onChange={e=>setNewStream(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addStream()}}} placeholder="Add a workstream, e.g. CPQ, Order-to-cash, Security review"/><button type="button" className="cp-secondary" onClick={addStream}>＋ Add</button></label></div>{message&&<div className="cp-message">{message}</div>}<button className="cp-primary" onClick={save}>Save engagement</button></section>
}

export function ScopeComparison({projectId}:{projectId:string}){
 const[rows,setRows]=useState<any[]>([]);useEffect(()=>{createClient().from("project_requirements").select("requirement_key,label,enabled,notes").eq("project_id",projectId).like("requirement_key","cp_scope_%").then(r=>setRows(r.data||[]))},[projectId]);
 if(!rows.length)return null;return <section className="cp-card"><p className="cp-kicker">SCOPE: THEN VS NOW</p><h3>What was sold vs. what was added</h3><div className="cp-scope-compare">{rows.filter(r=>r.enabled).map(r=><div key={r.requirement_key}><strong>{r.label}</strong><span className={r.notes==="added"?"added":"baseline"}>{r.notes==="added"?"Added later":"Original scope"}</span></div>)}</div></section>
}
