"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { ConsultationMeetings } from "@/components/consultation-meetings";
import { ConsultationEmail } from "@/components/consultation-email";
import { WorkstreamMilestones } from "@/components/consultation-workstream-milestones";
import { ChangeRegister, EngagementEditor, EvidenceLibrary, ReviewInbox, ScopeComparison } from "@/components/consultation-pilot-tools";

type Project={id:string;organization_id:string;name:string;project_type:string|null;baseline_start:string|null;target_finish:string|null;original_budget:number|null;status:string};
type EventRow={id:string;event_type:string;title:string;description:string|null;start_at:string|null;status:string|null;cost_impact:number|null;schedule_impact_days:number|null};
type Evidence={id:string;title:string|null;evidence_type:string;source_system:string|null;occurred_at:string|null;raw_text:string|null;created_at:string;storage_path?:string|null};
type Company={id:string;name:string;company_type:string|null};

const fmt=(v:string|null)=>{if(!v)return"Not set";const d=new Date(v.includes("T")?v:v+"T12:00:00");return d.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})};
const money=(v:number|null|undefined)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
const shift=(date:string|null,days:number)=>{if(!date)return null;const d=new Date(date+"T12:00:00");d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};

export function ConsultationWorkspace(){
 const[project,setProject]=useState<Project|null>(null),[events,setEvents]=useState<EventRow[]>([]),[evidence,setEvidence]=useState<Evidence[]>([]),[companies,setCompanies]=useState<Company[]>([]);
 const[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("Overview"),[showAdd,setShowAdd]=useState(false);
 const[entry,setEntry]=useState({type:"change",title:"",description:"",date:new Date().toISOString().slice(0,10),days:"",cost:"",status:"approved"});
 async function load(id?:string){
  const s=createClient(),auth=await s.auth.getUser();if(!auth.data.user){window.location.href="/consultationpath/login";return}
  const r=await s.from("projects").select("id,organization_id,name,project_type,baseline_start,target_finish,original_budget,status").order("created_at",{ascending:false});
  if(r.error){setError(r.error.message);setLoading(false);return}
  const list=(r.data||[]) as Project[],consulting=list.filter(p=>(p.project_type||"").toLowerCase().includes("consult")),wanted=id||new URLSearchParams(window.location.search).get("project")||"",p=consulting.find(x=>x.id===wanted)||consulting[0];
  if(!p){window.location.href="/consultationpath/setup";return} setProject(p);
  const [ev,doc,co]=await Promise.all([
   s.from("project_events").select("id,event_type,title,description,start_at,status,cost_impact,schedule_impact_days").eq("project_id",p.id).order("start_at",{ascending:true}),
   s.from("evidence").select("id,title,evidence_type,source_system,occurred_at,raw_text,created_at,storage_path").eq("project_id",p.id).order("created_at",{ascending:false}),
   s.from("companies").select("id,name,company_type").eq("organization_id",p.organization_id).order("name")
  ]);
  setEvents((ev.data||[]) as EventRow[]);setEvidence((doc.data||[]) as Evidence[]);setCompanies((co.data||[]) as Company[]);
  if(ev.error||doc.error||co.error)setError(ev.error?.message||doc.error?.message||co.error?.message||"Unable to load engagement");setLoading(false);
 }
 useEffect(()=>{load()},[]);
 const impactDays=useMemo(()=>events.filter(e=>e.event_type!=="baseline").reduce((n,e)=>n+(Number(e.schedule_impact_days)||0),0),[events]);
 const impactCost=useMemo(()=>events.filter(e=>e.event_type!=="baseline").reduce((n,e)=>n+(Number(e.cost_impact)||0),0),[events]);
 const currentTarget=project?shift(project.target_finish,impactDays):null,client=companies.find(c=>c.company_type==="client")?.name||"Client",changes=events.filter(e=>!["baseline","meeting"].includes(e.event_type));
 async function addEntry(e:FormEvent){e.preventDefault();if(!project)return;const s=createClient(),r=await s.from("project_events").insert({project_id:project.id,event_type:entry.type,title:entry.title,description:entry.description||null,start_at:entry.date||null,date_precision:"day",status:entry.status,cost_impact:entry.cost?Number(entry.cost.replace(/[^0-9.-]/g,"")):0,schedule_impact_days:entry.days?Number(entry.days):0});if(r.error){setError(r.error.message);return}setShowAdd(false);setEntry({type:"change",title:"",description:"",date:new Date().toISOString().slice(0,10),days:"",cost:"",status:"approved"});await load(project.id)}
 async function logout(){await createClient().auth.signOut();window.location.href="/consultationpath/login"}
 if(loading||!project)return <main className="cp-loading">Loading ConsultationPath…</main>;
 return <div className="cp-shell"><aside className="cp-sidebar"><div className="cp-brand"><span className="cp-mark">C</span><strong>Consultation<span>Path</span></strong></div><div className="cp-engagement"><small>WORKDAY ADAPTIVE PLANNING</small><strong>{project.name}</strong><span>{client}</span></div><nav>{["Overview","Workstreams","Timeline","Meetings","Email","Review Inbox","Changes & Decisions","Evidence","People","Engagement Data"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav><div className="cp-side-bottom"><span>{evidence.length} evidence · {changes.length} changes</span><button onClick={logout}>Log out</button></div></aside>
 <main className="cp-main"><header className="cp-top"><div><p className="cp-kicker">FP&A IMPLEMENTATION INTELLIGENCE</p><h1>{project.name}</h1><p>Models, dimensions, integrations, reporting, workforce planning, UAT and go-live changes — connected to evidence.</p></div><div className="cp-top-actions"><button className="cp-secondary" onClick={()=>window.print()}>Print summary</button><button className="cp-primary" onClick={()=>setShowAdd(true)}>＋ Record change</button></div></header>{error&&<div className="cp-message">{error}</div>}
 {showAdd&&<form className="cp-entry" onSubmit={addEntry}><div className="cp-entry-head"><div><p className="cp-kicker">NEW RECORD</p><h3>What changed?</h3></div><button type="button" onClick={()=>setShowAdd(false)}>×</button></div><div className="cp-entry-grid"><label>Type<select value={entry.type} onChange={e=>setEntry({...entry,type:e.target.value})}><option value="change">Scope change</option><option value="decision">Decision</option><option value="dependency">Client dependency</option><option value="risk">Risk</option><option value="milestone">Milestone movement</option></select></label><label>Date<input type="date" value={entry.date} onChange={e=>setEntry({...entry,date:e.target.value})}/></label><label className="wide">Title<input required value={entry.title} onChange={e=>setEntry({...entry,title:e.target.value})} placeholder="Add workforce planning to Phase 1"/></label><label className="wide">Details<textarea value={entry.description} onChange={e=>setEntry({...entry,description:e.target.value})} placeholder="Requested during design review; adds assumptions, model logic and UAT."/></label><label>Schedule impact (days)<input type="number" value={entry.days} onChange={e=>setEntry({...entry,days:e.target.value})}/></label><label>Fee impact<input value={entry.cost} onChange={e=>setEntry({...entry,cost:e.target.value})} placeholder="$7,500"/></label><label>Status<select value={entry.status} onChange={e=>setEntry({...entry,status:e.target.value})}><option value="approved">Approved</option><option value="pending">Pending approval</option><option value="open">Open</option><option value="complete">Complete</option></select></label><div className="wide cp-entry-actions"><button type="button" className="cp-secondary" onClick={()=>setShowAdd(false)}>Cancel</button><button className="cp-primary">Save to engagement history</button></div></div></form>}
 {tab==="Overview"&&<><section className="cp-summary"><div><span>Original go-live</span><strong>{fmt(project.target_finish)}</strong></div><div><span>Current forecast</span><strong>{fmt(currentTarget)}</strong></div><div><span>Schedule movement</span><strong className={impactDays?"cp-warn":""}>+{impactDays} days</strong></div><div><span>Fee impact</span><strong>{money(impactCost)}</strong></div></section><section className="cp-grid"><article className="cp-card cp-story"><p className="cp-kicker">WHY DID THE DATE MOVE?</p><h2>{impactDays?"The current forecast is "+impactDays+" days beyond the original go-live.":"No schedule movement has been recorded yet."}</h2><p>{impactDays?changes.length+" tracked changes, decisions, risks and client dependencies contribute to the current engagement story.":"Record scope changes and client dependencies as they happen; ConsultationPath will build the explanation."}</p><div className="cp-impact-row"><span>Scope / decisions <b>{changes.filter(x=>["change","decision"].includes(x.event_type)).reduce((n,x)=>n+(Number(x.schedule_impact_days)||0),0)} days</b></span><span>Client dependencies <b>{changes.filter(x=>x.event_type==="dependency").reduce((n,x)=>n+(Number(x.schedule_impact_days)||0),0)} days</b></span><span>Evidence <b>{evidence.length}</b></span></div></article><article className="cp-card"><p className="cp-kicker">RECENT CHANGES</p><h3>What changed from the baseline</h3>{changes.slice(-5).reverse().map(e=><div className="cp-change" key={e.id}><span>{fmt(e.start_at)}</span><div><strong>{e.title}</strong><small>{e.event_type} · {e.status||"open"}</small></div><b>{Number(e.schedule_impact_days)||0}d</b></div>)}{!changes.length&&<p className="cp-empty">No changes yet.</p>}</article></section><section className="cp-card"><p className="cp-kicker">ADAPTIVE PLANNING WORKSTREAMS</p><h3>Keep implementation scope visible</h3><div className="cp-workstreams"><span>Financial model</span><span>Workforce planning</span><span>Dimensions & hierarchies</span><span>Data integrations</span><span>Management reporting</span><span>UAT & training</span></div></section><ScopeComparison projectId={project.id}/></>}
 {tab==="Workstreams"&&<WorkstreamMilestones projectId={project.id}/>}\n {tab==="Timeline"&&<section className="cp-card"><p className="cp-kicker">ENGAGEMENT TIMELINE</p><h2>Baseline → changes → current forecast</h2><div className="cp-timeline">{events.map(e=><article key={e.id}><time>{fmt(e.start_at)}</time><i/><div><small>{e.event_type}</small><strong>{e.title}</strong><p>{e.description}</p>{e.schedule_impact_days?<b>+{e.schedule_impact_days} days</b>:null}</div></article>)}</div></section>}
 {tab==="Meetings"&&<ConsultationMeetings projectId={project.id} evidence={evidence} refresh={()=>load(project.id)}/>}\n {tab==="Email"&&<ConsultationEmail projectId={project.id}/>}
 {tab==="Review Inbox"&&<ReviewInbox projectId={project.id} refresh={()=>load(project.id)}/>}
 {tab==="Changes & Decisions"&&<><div className="cp-inline-action"><button className="cp-primary" onClick={()=>setShowAdd(true)}>＋ Record change</button></div><ChangeRegister events={events} refresh={()=>load(project.id)}/></>}
 {tab==="Evidence"&&<EvidenceLibrary projectId={project.id} evidence={evidence} refresh={()=>load(project.id)}/>}
 {tab==="People"&&<section className="cp-card"><p className="cp-kicker">ENGAGEMENT PARTICIPANTS</p><h2>Client and consulting organizations</h2>{companies.map(c=><div className="cp-evidence" key={c.id}><strong>{c.name}</strong><span>{c.company_type||"organization"}</span></div>)}</section>}
 {tab==="Engagement Data"&&<EngagementEditor project={project} companies={companies} refresh={()=>load(project.id)}/>}
 </main></div>
}