"use client";
import { useMemo,useState } from "react";

const events=[
{id:"1",date:"2026-07-06",type:"baseline",title:"Adaptive Planning implementation kickoff",status:"Approved",days:0,fee:0,description:"Original SOW: Core Financial Planning, 3 integrations, executive reporting, and UAT. Original go-live: September 30."},
{id:"2",date:"2026-07-21",type:"decision",title:"Use cost center as primary planning dimension",status:"Approved",days:0,fee:0,description:"Design decision confirmed during solution workshop."},
{id:"3",date:"2026-08-04",type:"change",title:"Add Workforce Planning to Phase 1",status:"Approved",days:8,fee:18500,description:"Client requested headcount and compensation planning be included before go-live."},
{id:"4",date:"2026-08-13",type:"dependency",title:"HRIS employee file delivered late",status:"Complete",days:5,fee:0,description:"Client dependency arrived five business days after the agreed data date."},
{id:"5",date:"2026-08-25",type:"change",title:"Add regional P&L reporting pack",status:"Approved",days:4,fee:7500,description:"Added 12 regional reporting views and management variance reports."},
{id:"6",date:"2026-09-03",type:"risk",title:"Chart of accounts hierarchy still changing",status:"Open",days:3,fee:0,description:"Finance continued restructuring account groupings during build."},
{id:"7",date:"2026-09-10",type:"dependency",title:"UAT participants unavailable",status:"Complete",days:4,fee:0,description:"Client requested UAT move by one week due to quarter-end priorities."},
{id:"8",date:"2026-09-18",type:"decision",title:"Move go-live to October 24",status:"Approved",days:0,fee:0,description:"Steering committee approved the revised go-live based on accumulated changes and dependencies."}
];
const evidence=[
{title:"Original SOW - FP&A Transformation",source:"SOW",date:"Jul 1",detail:"Signed baseline scope and September 30 go-live."},
{title:"Weekly Design Workshop - Aug 4",source:"Teams transcript",date:"Aug 4",detail:"Client asks to include Workforce Planning in Phase 1."},
{title:"HR Data Readiness Email",source:"Email",date:"Aug 11",detail:"Client confirms employee file will not be ready by agreed date."},
{title:"Reporting Requirements v3",source:"Excel",date:"Aug 25",detail:"Adds regional P&L and variance reporting requirements."},
{title:"Steering Committee - Sep 18",source:"Zoom transcript",date:"Sep 18",detail:"Revised go-live of October 24 approved."}
];
const meetings=[
{title:"Weekly Design Workshop",date:"Aug 4",source:"Microsoft Teams",summary:"Workforce Planning was requested for Phase 1. Consultant estimated 8 additional days and $18.5K."},
{title:"Data Readiness Review",date:"Aug 13",source:"Zoom",summary:"HRIS extract was still incomplete. Client committed to deliver corrected employee file by Aug 18."},
{title:"Reporting Workshop",date:"Aug 25",source:"Microsoft Teams",summary:"Regional P&L reporting expanded from 3 views to 12 views with new variance requirements."},
{title:"Steering Committee",date:"Sep 18",source:"Zoom",summary:"Team reviewed accumulated scope and dependency impact. October 24 go-live approved."}
];

export function ConsultationDemo(){
 const[t,setT]=useState("Overview");
 const impactDays=events.reduce((n,e)=>n+e.days,0),impactFee=events.reduce((n,e)=>n+e.fee,0);
 const changes=events.filter(e=>["change","dependency","risk","decision"].includes(e.type));
 const original=new Date("2026-09-30T12:00:00"),current=new Date(original);current.setDate(current.getDate()+impactDays);
 const currentDate=current.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});
 const grouped=useMemo(()=>({scope:events.filter(e=>e.type==="change").reduce((n,e)=>n+e.days,0),dependency:events.filter(e=>e.type==="dependency").reduce((n,e)=>n+e.days,0),risk:events.filter(e=>e.type==="risk").reduce((n,e)=>n+e.days,0)}),[]);
 return <div className="cp-shell cp-demo">
  <aside className="cp-sidebar"><div className="cp-brand"><span className="cp-mark">C</span><strong>Consultation<span>Path</span></strong></div><div className="cp-demo-badge">PUBLIC DEMO</div><div className="cp-engagement"><small>WORKDAY ADAPTIVE PLANNING</small><strong>Northstar Foods FP&A Transformation</strong><span>Northstar Foods, Inc.</span></div><nav>{["Overview","Timeline","Meetings","Email","Review Inbox","Changes & Decisions","Evidence","People","Engagement Data"].map(x=><button className={t===x?"active":""} key={x} onClick={()=>setT(x)}>{x}</button>)}</nav><div className="cp-side-bottom"><span>Demo data only</span><a href="/consultationpath/login">Sign in to ConsultationPath</a></div></aside>
  <main className="cp-main"><header className="cp-top"><div><p className="cp-kicker">FP&A IMPLEMENTATION INTELLIGENCE</p><h1>Northstar Foods FP&A Transformation</h1><p>Workday Adaptive Planning implementation · Core planning, workforce planning, integrations, reporting and UAT.</p></div><div className="cp-demo-actions"><button className="cp-secondary" onClick={()=>window.print()}>Print summary</button><button className="cp-primary" onClick={()=>alert("Demo mode: changes are not saved.")}>＋ Record change</button></div></header>
  {t==="Overview"&&<><section className="cp-summary"><div><span>Original go-live</span><strong>Sep 30, 2026</strong></div><div><span>Current forecast</span><strong>{currentDate}</strong></div><div><span>Schedule movement</span><strong className="cp-warn">+{impactDays} days</strong></div><div><span>Fee impact</span><strong>{"$"+impactFee.toLocaleString()}</strong></div></section><section className="cp-grid"><article className="cp-card cp-story"><p className="cp-kicker">WHY DID THE DATE MOVE?</p><h2>The implementation moved {impactDays} days beyond the original go-live.</h2><p>Two approved scope additions, two client dependencies and one active design risk explain the movement. Each item is tied to meeting or document evidence.</p><div className="cp-impact-row"><span>Added scope<b>{grouped.scope} days</b></span><span>Client dependencies<b>{grouped.dependency} days</b></span><span>Open design risk<b>{grouped.risk} days</b></span></div></article><article className="cp-card"><p className="cp-kicker">RECENT CHANGES</p><h3>What changed from the baseline</h3>{changes.slice(-5).reverse().map(e=><div className="cp-change" key={e.id}><span>{new Date(e.date+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric"})}</span><div><strong>{e.title}</strong><small>{e.type} · {e.status}</small></div><b>{e.days?("+"+e.days+"d"):"—"}</b></div>)}</article></section><section className="cp-card"><p className="cp-kicker">SCOPE: THEN VS NOW</p><h3>Adaptive Planning workstreams</h3><div className="cp-scope-compare"><div><strong>Financial model</strong><span className="baseline">Original scope</span></div><div><strong>Dimensions & hierarchies</strong><span className="baseline">Original scope</span></div><div><strong>Data integrations</strong><span className="baseline">Original scope</span></div><div><strong>Management reporting</strong><span className="baseline">Original scope</span></div><div><strong>UAT & training</strong><span className="baseline">Original scope</span></div><div><strong>Workforce planning</strong><span className="added">Added later</span></div></div></section></>}
  {t==="Timeline"&&<section className="cp-card"><p className="cp-kicker">ENGAGEMENT TIMELINE</p><h2>Baseline → changes → current forecast</h2><div className="cp-timeline">{events.map(e=><article key={e.id}><time>{new Date(e.date+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric"})}</time><i/><div><small>{e.type}</small><strong>{e.title}</strong><p>{e.description}</p>{e.days?<b>+{e.days} days</b>:null}</div></article>)}</div></section>}
  {t==="Meetings"&&<><section className="cp-card"><p className="cp-kicker">MEETING INGESTION</p><h2>Capture what the client actually said</h2><div className="cp-capture-options"><article><span>●</span><strong>Live microphone</strong><p>Capture live discussion in supported browsers.</p><button className="cp-primary" onClick={()=>alert("Demo only")}>● Start microphone</button></article><article><span>⇧</span><strong>Transcript file</strong><p>Import Zoom, Teams, Meet or transcript exports.</p><button className="cp-secondary" onClick={()=>alert("Demo only")}>Choose transcript</button></article><article><span>⌁</span><strong>Meeting apps</strong><p>Direct connections feed the same engagement history.</p><div className="cp-app-pills"><i>Zoom</i><i>Teams</i><i>Meet</i></div></article></div></section><section className="cp-card"><p className="cp-kicker">MEETING HISTORY</p>{meetings.map(m=><article className="cp-meeting-row" key={m.title}><div><strong>{m.title}</strong><span>{m.source} · {m.date}</span><p>{m.summary}</p></div><small>Transcript saved</small></article>)}</section></>}
  {t==="Email"&&<><section className="cp-card"><p className="cp-kicker">EMAIL INGESTION</p><h2>Project email flows into the same engagement memory</h2><div className="cp-email-connectors"><article><strong>Microsoft Outlook</strong><span>Connected mailbox rules</span><button className="cp-secondary" onClick={()=>alert("Demo only")}>Connected</button></article><article><strong>Gmail</strong><span>Filters and labels</span><button className="cp-secondary" onClick={()=>alert("Demo only")}>Connect Gmail</button></article><article><strong>Forwarding address</strong><span>Forward selected project mail</span><button className="cp-secondary" onClick={()=>alert("Demo only")}>Project inbox</button></article></div></section><section className="cp-card"><p className="cp-kicker">PROJECT EMAIL RULES</p><h3>What gets captured automatically</h3>{[{name:"Northstar client domain",detail:"From @northstarfoods.com · Copy to ConsultationPath"},{name:"Adaptive Planning project code",detail:'Subject contains "NSF Adaptive" · Label + copy'},{name:"Steering Committee",detail:"From Maya Chen or Daniel Ortiz · Copy attachments"}].map(x=><article className="cp-email-rule" key={x.name}><div><strong>{x.name}</strong><span>Outlook · Enabled</span><small>{x.detail}</small></div><div><button className="cp-link" onClick={()=>alert("Demo only")}>Edit</button></div></article>)}</section><section className="cp-card"><p className="cp-kicker">HOW EMAIL FLOWS</p><div className="cp-email-flow"><span>Inbox rule</span><b>→</b><span>Project email</span><b>→</b><span>Evidence</span><b>→</b><span>Review Inbox</span><b>→</b><span>Confirmed fact</span></div></section></>}
  {t==="Review Inbox"&&<section className="cp-card"><div className="cp-card-head"><div><p className="cp-kicker">MEETING REVIEW INBOX</p><h2>Confirm what the meeting changed</h2><p className="cp-muted">Examples of items ConsultationPath would surface from transcripts for consultant review.</p></div><span className="cp-count">3 pending</span></div>{[{type:"Scope change",title:"Add Workforce Planning to Phase 1",quote:"We really need headcount and compensation planning live in phase one, not phase two.",days:8,fee:18500},{type:"Client dependency",title:"HRIS employee file due Aug 18",quote:"We won't have the corrected employee file until next Tuesday.",days:5,fee:0},{type:"Decision",title:"Regional reporting required at go-live",quote:"Let's include the 12 regional P&L views in this release.",days:4,fee:7500}].map((x,i)=><article className="cp-candidate" key={i}><div className="cp-candidate-top"><span>{x.type}</span><small>{[94,89,91][i]}% confidence</small></div><label>Title<input value={x.title} readOnly/></label><label>What was said<textarea value={x.quote} readOnly/></label><div className="cp-candidate-grid"><label>Schedule impact<input value={x.days} readOnly/></label><label>Fee impact<input value={x.fee} readOnly/></label></div><div className="cp-candidate-actions"><button className="cp-secondary" onClick={()=>alert("Demo only")}>Reject</button><button className="cp-primary" onClick={()=>alert("Demo only")}>Confirm →</button></div></article>)}</section>}
  {t==="Changes & Decisions"&&<section className="cp-card"><p className="cp-kicker">CHANGE REGISTER</p><h2>Every material change, decision and dependency</h2><div className="cp-table"><div className="head"><span>Date</span><span>Type</span><span>Item</span><span>Status</span><span>Days</span><span>Fee</span></div>{changes.map(e=><div key={e.id}><span>{new Date(e.date+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric"})}</span><span>{e.type}</span><span><strong>{e.title}</strong><small>{e.description}</small></span><span>{e.status}</span><span>{e.days}</span><span>{e.fee?("$"+e.fee.toLocaleString()):"—"}</span></div>)}</div></section>}
  {t==="Evidence"&&<section className="cp-card"><p className="cp-kicker">SOURCE EVIDENCE</p><h2>What supports the engagement story</h2>{evidence.map(e=><div className="cp-evidence" key={e.title}><div><strong>{e.title}</strong><span>{e.source} · {e.date}</span><small>{e.detail}</small></div><button className="cp-link" onClick={()=>alert("Demo evidence preview")}>View</button></div>)}</section>}
  {t==="People"&&<section className="cp-card"><p className="cp-kicker">ENGAGEMENT PARTICIPANTS</p><h2>Client and consulting team</h2>{["Maya Chen — VP FP&A, Northstar Foods","Daniel Ortiz — Director of Finance, Northstar Foods","Priya Shah — Adaptive Planning Lead Consultant","Chris Morgan — Integration Consultant","Avery Brooks — Project Manager"].map(p=><div className="cp-evidence" key={p}><strong>{p}</strong></div>)}</section>}
  {t==="Engagement Data"&&<section className="cp-card"><p className="cp-kicker">ORIGINAL BASELINE</p><h2>What the engagement started as</h2><div className="cp-data"><span>Client<b>Northstar Foods, Inc.</b></span><span>Platform<b>Workday Adaptive Planning</b></span><span>Kickoff<b>Jul 6, 2026</b></span><span>Original go-live<b>Sep 30, 2026</b></span><span>Original contract value<b>$148,000</b></span><span>Current fee impact<b>+$26,000</b></span></div></section>}
  </main>
 </div>
}