"use client";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export function ConsultationLogin(){
 const[mode,setMode]=useState<"login"|"signup">("login");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const s=createClient();const r=mode==="login"?await s.auth.signInWithPassword({email,password}):await s.auth.signUp({email,password});setBusy(false);if(r.error){setMessage(r.error.message);return}if(mode==="signup"&&!r.data.session){setMessage("Account created. Check your email to confirm it, then sign in.");return}window.location.href="/consultationpath";}
 async function reset(){if(!email){setMessage("Enter your email first.");return}setBusy(true);const r=await createClient().auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+"/consultationpath/reset-password"});setBusy(false);setMessage(r.error?r.error.message:"Password reset email sent.");}
 return <main className="cp-auth"><section className="cp-auth-card"><div className="cp-brand"><span className="cp-mark">C</span><strong>Consultation<span>Path</span></strong></div><p className="cp-kicker">CLIENT ENGAGEMENT INTELLIGENCE</p><h1>{mode==="login"?"Welcome back":"Create your account"}</h1><p>Keep scope, decisions, client dependencies, evidence and delivery dates connected from kickoff through go-live.</p><form onSubmit={submit} className="cp-form"><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@consultingfirm.com"/></label><label>Password<input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)}/></label>{message&&<div className="cp-message">{message}</div>}<button className="cp-primary" disabled={busy}>{busy?"Working…":mode==="login"?"Sign in →":"Create account →"}</button></form>{mode==="login"&&<button className="cp-link cp-reset-link" onClick={reset}>Forgot password?</button>}<button className="cp-link" onClick={()=>{setMode(mode==="login"?"signup":"login");setMessage("")}}>{mode==="login"?"Don’t have an account? Create one":"Already have an account? Sign in"}</button></section><section className="cp-auth-hero"><div><p className="cp-kicker">THE MEMORY OF THE ENGAGEMENT</p><h2>When the date moves, know exactly why.</h2><p>ConsultationPath turns meetings, scope changes, approvals and client dependencies into an evidence-backed story of the project.</p></div></section></main>;
}